# Generated by Django 5.2.5 on 2025-08-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemorder',
            options={'verbose_name': 'Item-Order', 'verbose_name_plural': 'Item-Orders'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
